# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-11 23:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=b'', max_length=100)),
                ('slug', models.CharField(blank=True, default=b'', max_length=100)),
            ],
            options={
                'db_table': 'sites_site',
            },
            managers=[
                ('allSites', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SiteValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateTimeField(default=datetime.datetime.now)),
                ('aValue', models.FloatField(blank=True, default=0)),
                ('bValue', models.FloatField(blank=True, default=0)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'db_table': 'sites_sitevalues',
            },
            managers=[
                ('allSiteValues', django.db.models.manager.Manager()),
            ],
        ),
    ]
